#!/usr/bin/env bash
# Add a new line in the header
apt update -y
apt install nginx -y
sed -i "/listen \[::\]:80 default_server;/a\add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
service nginx restart
