#!/usr/bin/env bash
# Debug the server to make it work on the port 80 but on a shorter way
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo sed -i 's,pid /run/nginx.pid,pid /run/nginxx.pid,' /etc/nginx/nginx.conf
