#!/usr/bin/env bash
#The story of the /etc/passwd file
while IFS=":" read -r user pass uid gid name dir shell
do
echo "The user $user is part of the $gid gang, lives in $dir and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $name"
done < "/etc/passwd"
