#!/usr/bin/env bash
#Creating a Clock
minutes=1
hours=0
while [ "$hours" -ne 13 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ "$minutes" -lt 60 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done
